# --- Hugo 核心設定 ---
baseURL = 'https://NeoZPT.github.io/MyCoolBlog/'
languageCode = 'zh-TW'
title = '我的酷炫部落格'
theme = 'ananke'

# --- Ananke 主題專屬設定 ---
[params]
author = "NEO帥哥部落格"
description = "一段關於您網站的簡短描述。"
site_logo = "rocket.jpg"
github = "NeoZPT"

#fuckyou