# --- Hugo 核心設定 ---
# baseURL 已修正為正確的使用者名稱 Neo2PT
baseURL = 'https://NeoZPT.github.io/MyCoolBlog/'

languageCode = 'zh-TW'
title = '我的酷炫部落格'
theme = 'ananke'

# --- Ananke 主題專屬設定 ---
# [params] 下方每一行前面的無效空格都已移除
[params]
author = "NEO帥哥部落格"
description = "一段關於您網站的簡短描述。"

# 如果您有準備 logo 圖片，可以把它放在 static 資料夾，然後在這裡填上檔名
site_logo = "rocket.jpg"

# --- 社群連結 ---
# 這裡的 github 使用者名稱也一併修正
github = "NeoZPT"
